#!/usr/bin/env bash

set -o pipefail

backup_globals() {
	local filename="globals.sql.gz"
	(umask 077 && pg_dumpall -g -h "$PG_HOSTNAME" -U "$PG_USERNAME" -p "$PG_PORT" | gzip > "${filename}.in_progress") \
	&& mv "${filename}.in_progress" "$filename"
}


list_databases() {
	local databases_query="select datname from pg_database where not datistemplate and datallowconn order by datname;"
	psql -h "$PG_HOSTNAME" -U "$PG_USERNAME" -p "$PG_PORT" -At -c "$databases_query" postgres
}


backup_databases() {
	local databases=$(list_databases)
	if [[ -z "${databases// }" ]]; then
		echo "Found no databases to back up. Exiting."
		exit 1
	fi
	while read -r database; do
		local filename="${database}.custom"
		if (umask 077 && pg_dump -F c -h "$PG_HOSTNAME" -U "$PG_USERNAME" -p "$PG_PORT" "$database" -f "${filename}.in_progress"); then
			mv "${filename}.in_progress" "$filename"
		else
			return 1
		fi;
	done <<< "$databases"
	return 0
}


print_usage() {
	echo "Usage:"
	echo "    $0 <configuration_file>"
	exit 1
}


load_config_file() {
	local config_file="$1"

	if [[ ! -r "$config_file" ]]; then
		echo "Unable to read configuration file at \"${config_file}\"." 1>&2
		exit 1
	fi;

	source "$config_file"
}


create_output_dir() {
	local output_dir="${OUTPUT_DIR_BASE%/}/$(date "+$DATE_FORMAT")"
	mkdir -p "$output_dir"
	echo "$output_dir"
}


main() {
	if [[ $# -ne 1 ]]; then
		print_usage "$0"
		exit
	fi

	local config_file="$1"
	load_config_file "$config_file" && echo "Loaded configuration from \"${config_file}\"."

	output_dir="$(create_output_dir)"
	echo "Created output directory \"${output_dir}\"."

	pushd . >/dev/null
	cd "$output_dir"

	if [[ "$DO_BACKUP_GLOBALS" = true ]]; then
		echo "Starting globals backup."
		if backup_globals; then
			echo "Globals backup is done."
		else
			echo "Globals backup failed. Exiting."
			exit 1;
		fi;
	else
		echo "Skipping globals backup."
	fi;

	echo "Starting databases backup."
	if backup_databases; then
		echo "Databases backup is done."
	else
		echo "Databases backup failed. Exiting."
		exit 1;
	fi;

	popd >/dev/null
}


main "$@"
